const routePath = {
  home: '/',
  aboutUs: '/about-us',
  faq: '/faq',
  forgetPassword: '/forget-password',
  login: '/login',
  user: '/user/:id',
  userCollects: '/user/collects',
  userOrders: '/user/orders',
  userPersonalSettings: '/user/personal-settings',
  userProjects: '/user/projects',
  userTeamSettings: '/user/team-settings',
  newPassword: '/new-password',
  notifications: '/notifications',
  proposal: '/proposal',
  proposalForm: '/proposal/form',
  proposalId: '/proposal/[id]',
  team: '/team',
  projects: '/projects',
  projectsIntroduction: '/projects/introduction',
  projectsNews: '/projects/news',
  projectsQuestions: '/projects/questions',
  projectsMsgBoard: '/projects/msg-board',
  signup: '/signup',
  userPrivacy: '/user-privacy',
  userTerms: '/user-terms',
};

export default routePath;
